language: c

env:
  - LIBAV=libav-stable
  - LIBAV=libav-git
  - LIBAV=ffmpeg-stable
  - LIBAV=ffmpeg-git
compiler:
  - clang
branches:
  only:
    - master
    - ci

before_install: ./travis-deps libass-stable $LIBAV
script:
  - ./bootstrap.py
  - ./waf configure
  - ./waf build

notifications-policy: &notifications-policy
  on_success: change
  on_failure: always

notifications:
  irc:
    channels:
      - "irc.freenode.org#mpv-player-dev"
    <<: *notifications-policy
