[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "F", # pyflakes
    "E", "W", # pycodestyle
    "I", # pycodestyle
    "N", # pep8-naming
    "UP", # pyupgrade
    "A", # flake8-builtins
    "Q", # flake8-quotes
]
